server:
  port: 8881
Spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      label: master
      profile: dev
      uri: http://localhost:8888/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/